export const MovieCollections = [
  {
    adult: false,
    backdrop_path: "/yMJn2vWKAAzZzlewJm5pPWHUWL3.jpg",
    id: 623911,
    name: "Captain Marvel Collection",
    original_language: "en",
    original_name: "Captain Marvel Collection",
    overview:
      "Captain Marvel is an American superhero film series based on the Marvel Comics character Carol Danvers. The films are produced by Marvel Studios and distributed by Walt Disney Studios Motion Pictures.",
    poster_path: "/vMacLMNqwbP5eQ9KGpZE9ZqgCIk.jpg",
  },
  {
    adult: false,
    backdrop_path: "/awxAczgOQG8TZzBAVE3a9nwoIeA.jpg",
    id: 627234,
    name: "Marvel Rising Collection",
    original_language: "en",
    original_name: "Marvel Rising Collection",
    overview:
      "Superpowered teens join forces as an unlikely, but formidable crew of aspiring heroes in the Marvel Universe.",
    poster_path: "/91iNRP94GAVstIqc2zN1KwPt1FI.jpg",
  },
  {
    adult: false,
    backdrop_path: "/r1Q3jyOpfbF3VDU52w8RzkTPbfe.jpg",
    id: 76122,
    name: "Marvel One-Shot: The Consultant",
    original_language: "en",
    original_name: "Marvel One-Shot: The Consultant",
    overview:
      "Agent Coulson informs Agent Sitwell that the World Security Council wishes Emil Blonsky to be released from prison to join the Avengers Initiative. As Nick Fury doesn't want to release Blonsky, the two agents decide to send a patsy to sabotage the meeting...",
    poster_path: "/xqNLXUUvBnfVk6m3QFGGU0Grgs7.jpg",
  },
  {
    adult: false,
    backdrop_path: "/FQETJbf4a1btUAW1qlYRvu8Tho.jpg",
    id: 752937,
    name: "LEGO Marvel Super Heroes Collection",
    original_language: "en",
    original_name: "LEGO Marvel Super Heroes Collection",
    overview: "A collection of all the LEGO Marvel Super Heroes movies.",
    poster_path: "/fRIBCOHPhXraUOlv9wTjSaLSr8x.jpg",
  },
  {
    adult: false,
    backdrop_path: "/AvnqpRwlEaYNVL6wzC4RN94EdSd.jpg",
    id: 531241,
    name: "Spider-Man (MCU) Collection",
    original_language: "en",
    original_name: "Spider-Man (MCU) Collection",
    overview:
      "A superhero film series based on the Marvel character Spider-Man, portrayed by Tom Holland. The series is centered on Peter Parker, an academically gifted but socially inept high school student who fights crime as Spider-Man, a member of The Avengers.",
    poster_path: "/yeba3Y820OjApZO9aJevDsNeMEd.jpg",
  },
  {
    adult: false,
    backdrop_path: "/zuW6fOiusv4X9nnW3paHGfXcSll.jpg",
    id: 86311,
    name: "The Avengers Collection",
    original_language: "en",
    original_name: "The Avengers Collection",
    overview:
      "A superhero film series produced by Marvel Studios based on the Marvel Comics superhero team of the same name, and part of the Marvel Cinematic Universe (MCU).  The series features an ensemble cast from the Marvel Cinematic Universe series films, as they join forces for the peacekeeping organization S.H.I.E.L.D. led by Nick Fury.",
    poster_path: "/5LkXlUPrRuhMAeVugr1xXcsZbV8.jpg",
  },
  {
    adult: false,
    backdrop_path: "/4z9ijhgEthfRHShoOvMaBlpciXS.jpg",
    id: 10,
    name: "Star Wars Collection",
    original_language: "en",
    original_name: "Star Wars Collection",
    overview:
      'An epic space-opera theatrical film series, which depicts the adventures of various characters "a long time ago in a galaxy far, far away…."',
    poster_path: "/aSrMJYmQX8kpF26LijkCsYhBMvm.jpg",
  },
  {
    adult: false,
    backdrop_path: "/zU0W0VRF0ZkN8CvjW4LGw0oSyTa.jpg",
    id: 302331,
    name: "LEGO Star Wars Collection",
    original_language: "en",
    original_name: "LEGO Star Wars Collection",
    overview: "A set of animated LEGO movies based on the Star Wars universe.",
    poster_path: "/sHlgKW5hlQvwJseJkmnkSmL3YDI.jpg",
  },
  {
    adult: false,
    backdrop_path: null,
    id: 141748,
    name: "Robot Chicken - Star Wars Collection",
    original_language: "en",
    original_name: "Robot Chicken - Star Wars Collection",
    overview:
      "A series of Robot Chicken TV films parodying the Star Wars films.",
    poster_path: "/m6tP4z5IIk8lIsBTpXu5H0B8hO3.jpg",
  },
  {
    adult: false,
    backdrop_path: "/cVYUqWzzUSrkLQwb4jlWAkaFCAX.jpg",
    id: 1004630,
    name: "LEGO Star Wars (Seasonal) Collection",
    original_language: "en",
    original_name: "LEGO Star Wars (Seasonal) Collection",
    overview:
      "A collection of LEGO Stars Wars seasonal specials released on Disney+.",
    poster_path: "/jHITUzB6fZVOYZ13YCqVTS06iyw.jpg",
  },
  {
    adult: false,
    backdrop_path: "/VXwSW7UGuNScCTy5V5H9pgioir.jpg",
    id: 133830,
    name: "Star Wars: The Ewok Adventures Collection",
    original_language: "en",
    original_name: "Star Wars: The Ewok Adventures Collection",
    overview:
      "The Ewok Adventures is a 1984 American made-for-TV film duology based in the Star Wars setting. It was released theatrically in Europe as Caravan of Courage: An Ewok Adventure, and is known by that title today. The film focuses on the struggles of a brother and sister, stranded on the forest moon of Endor, in locating their parents, who have been kidnapped by a monster known as the Gorax. The film is set sometime between the fifth and sixth episodes of the Star Wars saga. It is the first of two spin-off films featuring the Ewoks from Star Wars Episode VI: Return of the Jedi. A sequel to this movie released in 1985. While the sequel's working title was simply Ewoks II, it was released as Ewoks: The Battle for Endor.",
    poster_path: "/vSrIbcWQJ3IL0R5DoWLh0c7HMTz.jpg",
  },
  {
    adult: false,
    backdrop_path: null,
    id: 423877,
    name: "The Man Who Saved the World Collection",
    original_language: "en",
    original_name: "Dünyayı Kurtaran Adam Koleksiyonu",
    overview:
      "Dünyayı Kurtaran Adam (The Man Who Saved the World) and Dünyayi Kurtaran Adam'in Oglu (The Son of the Man who Saved the World) is a series of Turkish adventure films also known as Turkish Star Wars because of its notorious use of unauthorized footage from Star Wars and other movies worked into the film.",
    poster_path: "/bq8NBaPz1dbv4B1xWV7pGhXcixc.jpg",
  },
  {
    adult: false,
    backdrop_path: "/dOSECZImeyZldoq0ObieBE0lwie.jpg",
    id: 645,
    name: "James Bond Collection",
    original_language: "en",
    original_name: "James Bond Collection",
    overview:
      "The James Bond Collection is a legendary spy film series based on Ian Fleming’s novels, following MI6 agent 007, James Bond, as he takes on global threats with style, gadgets, and charm. Produced by EON Productions, the franchise spans 25 official films (1962–2021) and has featured six actors, from Sean Connery to Daniel Craig. Known for its thrilling action, iconic villains, Bond girls, and unforgettable theme songs, the series remains a cornerstone of the spy genre. With espionage, luxury cars, and shaken-not-stirred martinis, Bond continues to captivate audiences worldwide.",
    poster_path: "/ofwSiqOFShhunAIYYdSMHMJQSx2.jpg",
  },
  {
    adult: false,
    backdrop_path: "/kmEsQL2vOTA0jnM28fXS45Ky8kX.jpg",
    id: 1241,
    name: "Harry Potter Collection",
    original_language: "en",
    original_name: "Harry Potter Collection",
    overview:
      "The Harry Potter films are a fantasy series based on the series of seven Harry Potter novels by British writer J. K. Rowling.",
    poster_path: "/eVPs2Y0LyvTLZn6AP5Z6O2rtiGB.jpg",
  },
  {
    adult: false,
    backdrop_path: null,
    id: 1173608,
    name: "The Making of The Lord of the Rings Collection",
    original_language: "en",
    original_name: "The Making of The Lord of the Rings Collection",
    overview:
      'Created by filmmaker Costa Botes (personally selected by Peter Jackson), this documentary uses raw footage to reveal the inside story on how the greatest adventure film franchise was born. Originally included as a bonus feature with "The Lord of the Rings - Limited Edition" DVD sets, later rarely released again.',
    poster_path: "/xMXBHnV7sqsLOZ8rNPLc3TGNe0O.jpg",
  },
  {
    adult: false,
    backdrop_path: "/8rKJzqBVUbcshKROW4pamVSt1UO.jpg",
    id: 141290,
    name: "The Lord of the Rings (Animated) Collection",
    original_language: "en",
    original_name: "The Lord of the Rings (Animated) Collection",
    overview:
      "A collection of the animated The Lord of the Rings movies by Rankin/Bass.",
    poster_path: "/yLzL7Pv4ZAJ81QD6esn0AqdNgzr.jpg",
  },
  {
    adult: false,
    backdrop_path: "/bccR2CGTWVVSZAG0yqmy3DIvhTX.jpg",
    id: 119,
    name: "The Lord of the Rings Collection",
    original_language: "en",
    original_name: "The Lord of the Rings Collection",
    overview:
      "The Lord of the Rings trilogy consists of three epic fantasy films, based on the influential novels written by J. R. R. Tolkien, directed by Peter Jackson.",
    poster_path: "/249qw7r9E31vvOSeMQoOrjxMjfm.jpg",
  },
  {
    adult: false,
    backdrop_path: "/z5A5W3WYJc3UVEWljSGwdjDgQ0j.jpg",
    id: 9485,
    name: "The Fast and the Furious Collection",
    original_language: "en",
    original_name: "The Fast and the Furious Collection",
    overview:
      "An action film series centered on illegal street racing and heists.",
    poster_path: "/zOCnMPoUxgJK1RFPfN4PcnT16gr.jpg",
  },
  {
    adult: false,
    backdrop_path: "/mroWh717g0Ah2c0rrPGW6f3EWMM.jpg",
    id: 87359,
    name: "Mission: Impossible Collection",
    original_language: "en",
    original_name: "Mission: Impossible Collection",
    overview:
      "Mission: Impossible is a series of a secret agent thriller films based on the popular 1966–73 television series. They chronicle the missions of a team of secret government agents known as the Impossible Missions Force (IMF) under the leadership of agent Ethan Hunt.",
    poster_path: "/geEjCGfdmRAA1skBPwojcdvnZ8A.jpg",
  },
  {
    adult: false,
    backdrop_path: "/xyhrCEdB4XRkelfVsqXeUZ6rLHi.jpg",
    id: 263,
    name: "The Dark Knight Collection",
    original_language: "en",
    original_name: "The Dark Knight Collection",
    overview:
      "With minimal usage of CGI and a focus on character driven narratives, Christopher Nolan's dark, gritty portrayal of Bruce Wayne's transition into Batman and his struggles as Gotham's superhero set the precedent for modern superhero films.",
    poster_path: "/ogyw5LTmL53dVxsppcy8Dlm30Fu.jpg",
  },
  {
    adult: false,
    backdrop_path: "/bNLLjc6NT80FmFknvHn8demDHhl.jpg",
    id: 248534,
    name: "Batman: The Dark Knight Returns Collection",
    original_language: "en",
    original_name: "Batman: The Dark Knight Returns Collection",
    overview:
      'Batman: The Dark Knight Returns is a two-part animated superhero film, an adaptation of the 1986 comic book "The Dark Knight Returns" by Frank Miller.',
    poster_path: "/5IsknQ6brdqMwxDbPEiXhEskxI0.jpg",
  },
  {
    adult: false,
    backdrop_path: "/oC5S5pdfzPiQC4us05uDMT7v5Ng.jpg",
    id: 573436,
    name: "Spider-Man: Spider-Verse Collection",
    original_language: "en",
    original_name: "Spider-Man: Spider-Verse Collection",
    overview:
      "An animated trilogy of Spider-Man films helmed by writers Phil Lord and Christopher Miller. The films follow Miles Morales and Gwen Stacy as they deal with various iterations of Spider-Man throughout the vast and infinite multiverse.",
    poster_path: "/eD4bGQNfmqExIAzKdvX5gDHhI2.jpg",
  },
  {
    adult: false,
    backdrop_path: "/waZqriYTuBE3WqXI3SDGi3kfDQE.jpg",
    id: 556,
    name: "Spider-Man Collection",
    original_language: "en",
    original_name: "Spider-Man Collection",
    overview:
      "A superhero film series based on the Marvel Comics character Spider-Man. The series is centered on Peter Parker, an academically gifted but socially inept freelance photographer who gets bitten by a genetically modified spider and gains spider-like abilities, all of which he uses to fight crime as a spider-masked vigilante, learning for himself that with great power comes great responsibility.",
    poster_path: "/bp5PqLa06QA1LsELA1SsKZ008H7.jpg",
  },
  {
    adult: false,
    backdrop_path: "/rkVIb2JS3C2DBtjX8szbg37Qwff.jpg",
    id: 225941,
    name: "Spider-Man (TV) Collection",
    original_language: "it",
    original_name: "Spider-Man (TV) Collection",
    overview:
      "Made for TV pilot and two 2 part episodes loosely referred to as sequels (The Deadly Dust and The Chinese Web).",
    poster_path: "/vAw4x1XMCIN2EPL5febhNsKygya.jpg",
  },
  {
    adult: false,
    backdrop_path: "/AvnqpRwlEaYNVL6wzC4RN94EdSd.jpg",
    id: 531241,
    name: "Spider-Man (MCU) Collection",
    original_language: "en",
    original_name: "Spider-Man (MCU) Collection",
    overview:
      "A superhero film series based on the Marvel character Spider-Man, portrayed by Tom Holland. The series is centered on Peter Parker, an academically gifted but socially inept high school student who fights crime as Spider-Man, a member of The Avengers.",
    poster_path: "/yeba3Y820OjApZO9aJevDsNeMEd.jpg",
  },
  {
    adult: false,
    backdrop_path: "/40RZP4mEel441OVcNyFCTFzHi4o.jpg",
    id: 50410,
    name: "Spider-Man: The Venom Saga",
    original_language: "en",
    original_name: "Spider-Man: The Venom Saga",
    overview:
      "A space-shuttle crash-landing puts the famous web-slinger Spider-Man in contact with a living alien substance that bonds to his suit and enhances his super-powers. Unfortunately, the alien substance begins to change him and he feels the pull of evil, so discards the suit. The evil attaches itself to another host leading to an epic confrontation between good and evil.",
    poster_path: "/vvYt1CDagCKMrolohME0o15GPZ3.jpg",
  },
  {
    adult: false,
    backdrop_path: "/aLrNTcLN2kDu9jAJ4tS5haiWGc6.jpg",
    id: 125574,
    name: "The Amazing Spider-Man Collection",
    original_language: "en",
    original_name: "The Amazing Spider-Man Collection",
    overview:
      "A superhero film series based on the Marvel Comics character Spider-Man. The series is centered on Peter Parker, a teenager struggling to find his place in life ever since his parents disappeared when he was a child. A spider bites him on the back of his neck, giving him spider-powers. It is a reboot of Sony's Spider-Man film franchise.",
    poster_path: "/rpS1w85pIZIIiKqss9gZFVR0qEG.jpg",
  },
  {
    adult: false,
    backdrop_path: "/hApclyB9NEZEQujAVajzi5iWE4a.jpg",
    id: 10194,
    name: "Toy Story Collection",
    original_language: "en",
    original_name: "Toy Story Collection",
    overview:
      "Toy Story is a CGI animated media franchise created by Pixar and distributed by Walt Disney Pictures. The franchise is based on the anthropomorphic concept that all toys, unknown to humans, are secretly alive, and the films focus on a diverse group of toys that feature a classic cowboy named Sheriff Woody and a modern spaceman named Buzz Lightyear. The group unexpectedly embark on adventures that challenge and change them.  The collection currently includes Toy Story 1-4.",
    poster_path: "/rki5qLuwb0xnnE9seehxO9TlLhW.jpg",
  },
  {
    adult: false,
    backdrop_path: "/wxgD3fB5lQ2sGJLog0rvXW049Pf.jpg",
    id: 295,
    name: "Pirates of the Caribbean Collection",
    original_language: "en",
    original_name: "Pirates of the Caribbean Collection",
    overview:
      "A series of fantasy swashbuckler films based on Walt Disney's theme park ride of the same name. The films follow the adventures of Captain Jack Sparrow and take place in a world ruled by the British Empire, the East India Trading Company and the Spanish Empire, with pirates representing freedom from the ruling powers.",
    poster_path: "/4KUJ38SsViJTsUmTRvXxerBNwAv.jpg",
  },
  {
    adult: false,
    backdrop_path: "/s4xWmz9PEjPERSRcd7H7xMJpYvE.jpg",
    id: 84,
    name: "Indiana Jones Collection",
    original_language: "en",
    original_name: "Indiana Jones Collection",
    overview:
      'Adventure film series created by George Lucas and Philip Kaufman starring Harrison Ford as archaeologist Dr. Henry Walton "Indiana" Jones, Jr., and directed by Steven Spielberg and James Mangold. Spanning the globe, on death-defying archeological endeavors, if adventure has a name... it must be Indiana Jones.',
    poster_path: "/yJgGZ8YtSIUuTIwYBCs1TjcVrg4.jpg",
  },
  {
    adult: false,
    backdrop_path: "/iZScbVabDDKlQteQc8dIyqXMDz.jpg",
    id: 222041,
    name: "The Adventures of Young Indiana Jones: Travels with Father",
    original_language: "en",
    original_name: "The Adventures of Young Indiana Jones: Travels with Father",
    overview:
      "While visiting Russia on his father’s lecture tour, Indy runs off on his own and meets Leo Tolstoy. Later, on a trip to Athens, Indy and his father are forced together by circumstance when they get into a bind in the monasteries of Meteora, where they share some memorable moments.",
    poster_path: "/mn8PQOyUiuFw2BBbVNqsUHk5iuF.jpg",
  },
  {
    adult: false,
    backdrop_path: "/mDMCET9Ens5ANvZAWRpluBsMAtS.jpg",
    id: 230,
    name: "The Godfather Collection",
    original_language: "en",
    original_name: "The Godfather Collection",
    overview:
      "Francis Ford Coppola’s trilogy films about the everyday life of a New York mafia family. With its star-studded cast these films would go down in history as some of the greatest Hollywood has ever produced.",
    poster_path: "/zVb22YOMgljCEYbXlvCvEiN4VwT.jpg",
  },
  {
    adult: false,
    backdrop_path: "/c9C9Pg2QctyjZHRmS0P8rZg1OTA.jpg",
    id: 264,
    name: "Back to the Future Collection",
    original_language: "en",
    original_name: "Back to the Future Collection",
    overview:
      "An American science fiction–comedy film series that follows the adventures of a high school student, Marty McFly and an eccentric scientist, Dr Emmett L. Brown as they use a DeLorean time machine to time travel to different periods in the history of Hill Valley, California.",
    poster_path: "/5Xsu2o5IsZRuuxCEVZ9nVve21FP.jpg",
  },
  {
    adult: false,
    backdrop_path: "/bRm2DEgUiYciDw3myHuYFInD7la.jpg",
    id: 2344,
    name: "The Matrix Collection",
    original_language: "en",
    original_name: "The Matrix Collection",
    overview:
      "The Matrix collection depicts a complex science fiction story incorporating many philosophical elements. Written and directed by the Wachowskis and produced by Joel Silver.",
    poster_path: "/bV9qTVHTVf0gkW0j7p7M0ILD4pG.jpg",
  },
  {
    adult: false,
    backdrop_path: "/ykVHlrE3aSvHYeIXOrWDsYZ18vv.jpg",
    id: 748,
    name: "X-Men Collection",
    original_language: "en",
    original_name: "X-Men Collection",
    overview:
      "A superhero film series about a team of mutant superheroes based on the Marvel Comics superheroes of the same name.",
    poster_path: "/31rqs6ZxFdi5nWZZaFPIr17q8jt.jpg",
  },
  {
    adult: false,
    backdrop_path: "/Ipp7cegtub4t0mu7xaKLQkYoGc.jpg",
    id: 131635,
    name: "The Hunger Games Collection",
    original_language: "en",
    original_name: "The Hunger Games Collection",
    overview:
      "A science fiction film series based on the novel of the same name by Suzanne Collins. The film series takes place in a dystopian post-apocalyptic future in the nation of Panem, featuring the protagonist, Katniss Everdeen.",
    poster_path: "/fPer2U4uQT1dkXTUWODDaLECWoW.jpg",
  },
  {
    adult: false,
    backdrop_path: "/s3vdRkK7KZFUDC8HEJo2GRKyVhW.jpg",
    id: 386382,
    name: "Frozen Collection",
    original_language: "de",
    original_name: "Frozen Collection",
    overview:
      'The Frozen Collection includes the enchanting adventures of sisters Elsa and Anna, set in the magical kingdom of Arendelle. This captivating series features the beloved animated films "Frozen" and "Frozen 2", as well as the charming short films "Frozen Fever" and "Olaf\'s Frozen Adventure". Join Elsa, Anna, Olaf, and other unforgettable characters as they embark on journeys of self-discovery, friendship, and love while overcoming various challenges and obstacles.',
    poster_path: "/13Op41T3cALJedrKqYPrlc3cIbO.jpg",
  },
];
